# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d0e0752ed73d082a33a40f9ff421c07b6933801c82291c72c206fb4d81628f59f8e7961ccf2d863aff151cca71294df1e02fd80d35cece1fae635f1aef8689

test:
  secret_key_base: 68b334450e15202f7dc38e52527389a76af2c47db1ed00d60e9da77896c2c90e8570910657c955d7441b9db6a68cfc80e93074e2dbca3a5d3c04909f732cfcbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
