# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  secret_key_base: '0340f0b45689ca19aa4019021b6245cc0e695a71f0aac4e42986a3e3c8c37dcc07bfcb2389a53d69d7622cc85c0d4027afa23a0c94d5fb382ff88740f5c405c8'

test:
  secret_key_base:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
