# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59572be9531026824d11f454d9af901c1ae796f99be0ea4a427933680440abc044827ca60e33343f2e2d3dfa67b3fd184b4900619039bd72ccaf443ed57977b8

test:
  secret_key_base: 43787cfe25fa6db971b7b6a0a98db4463ffa2dbc9c51b90c700b8609a8939f186ddf23b657ceddb96b560e9943893b2db5303b0207d0847fff0c206cb21c12a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
